# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-24 07:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.TextField(max_length=3)),
                ('name', models.TextField(max_length=100)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deal_id', models.TextField(blank=True, max_length=40, null=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_clearing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sell_amount', models.IntegerField()),
                ('buy_amount', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sell_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_currency', to='bos.Currency')),
            ],
        ),
    ]
