# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-24 07:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('symbol', models.TextField(max_length=3)),
                ('name', models.TextField(max_length=100)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, b'Married'), (2, b'Single'), (3, b'Divorce'), (4, b'Relevant')], default=2)),
                ('gender', models.IntegerField(choices=[(1, b'Male'), (2, b'Female'), (3, b'Other')], default=1)),
                ('level_study', models.IntegerField(choices=[(1, b'Undergrad'), (2, b'Grad'), (3, b'High school')], default=1)),
                ('etnicity', models.IntegerField(choices=[(1, b'White'), (2, b'African American'), (3, b'Hispanic'), (4, b'Asian'), (5, b'Other')], default=1)),
                ('email', models.TextField(max_length=40, unique=True)),
                ('birth_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.TextField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deal_id', models.TextField(blank=True, max_length=40, null=True, unique=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_clearing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sell_amount', models.FloatField()),
                ('buy_amount', models.FloatField()),
                ('rate', models.FloatField()),
                ('buy_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_currency', to='bos.Currency')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sell_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_currency', to='bos.Currency')),
            ],
        ),
    ]
