# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-24 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('choice_text', models.TextField(max_length=40)),
                ('choice_value', models.TextField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPartner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bos.CompanyPartner')),
                ('questions', models.ManyToManyField(to='bos.Question')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='surveys',
            field=models.ManyToManyField(blank=True, null=True, to='bos.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bos.Question'),
        ),
    ]
