# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bos', '0002_auto_20170703_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='buy_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_currency', to='bos.Currency'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='deal_id',
            field=models.TextField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
