# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bos', '0003_auto_20170711_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='sell_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell_currency', to='bos.Currency'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='buy_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_currency', to='bos.Currency'),
        ),
    ]
