# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-24 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bos', '0003_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='question_choice',
            field=models.ManyToManyField(to='bos.Choice'),
        ),
    ]
