# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-24 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bos', '0004_auto_20180324_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(max_length=40)),
                ('point_rewarded', models.FloatField(null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bos.CompanyPartner')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='point_reward',
            field=models.FloatField(null=True),
        ),
    ]
