# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-15 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bos', '0004_auto_20170711_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='buy_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sell_amount',
            field=models.FloatField(),
        ),
    ]
