# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-24 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bos', '0005_auto_20180324_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bos.Question'),
        ),
    ]
