# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-25 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bos', '0007_companypartner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='title',
            field=models.TextField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='point_rewarded',
            field=models.FloatField(default=10, null=True),
        ),
    ]
