# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-25 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bos', '0008_auto_20180324_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='profiles',
            field=models.ManyToManyField(null=True, to='bos.Profile'),
        ),
    ]
